spring:
  mail:
    host: smtp.ethereal.email
    port: 587
    username: dax47@ethereal.email
    password: bQxghhmVwcdGhhePb3

co:
  leapwise:
    banking:
      number-of-transactions: 1000
      generated-file-name: transactions.txt
      monthly-turnover-job-cron: "*/5 * * ? * *"

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
