co:
  leapwise:
    banking:
      number-of-transactions: 100
      generated-file-name: transactions.txt
      monthly-turnover-job-cron: "*/5 * * ? * *"

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
